from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv

APP_VERSION = "64_full_GMAIL_PORT80_PROBE_DUAL_PERSISTENCE"


def _normalize_public_base_url(value: str) -> str:
    """Return one external HTTPS base URL without callback/health paths.

    Coolify may expose its wildcard URL to the container with an ``http``
    scheme even though users reach the reverse proxy over HTTPS. Google OAuth
    requires HTTPS for ``gmail.send``, so non-local hosts are always normalized
    to HTTPS. Port 80/443 and known endpoint suffixes are removed.
    """
    from urllib.parse import urlsplit, urlunsplit

    value = (value or "").strip().strip('"\'')
    if not value:
        return ""
    value = value.split(",", 1)[0].strip()
    if "://" not in value:
        value = f"https://{value}"

    parsed = urlsplit(value)
    host = (parsed.hostname or "").lower()
    if not host:
        return ""
    local_hosts = {"localhost", "127.0.0.1", "::1"}
    scheme = parsed.scheme.lower() or "https"
    if host not in local_hosts:
        scheme = "https"

    port = parsed.port
    if port in {80, 443}:
        port = None
    netloc = host if port is None else f"{host}:{port}"

    path = parsed.path.rstrip("/")
    for suffix in ("/gmail/callback", "/healthz"):
        if path.endswith(suffix):
            path = path[: -len(suffix)].rstrip("/")
            break
    return urlunsplit((scheme, netloc, path, "", "")).rstrip("/")


def _resolve_gmail_public_base_url() -> str:
    """Resolve the public URL generated by Coolify.

    v64 deliberately listens on container port 80. This avoids custom-port
    proxy routing entirely: Coolify's standard ``SERVICE_URL_<ID>`` route can
    reach the callback server without a manual Domains field or ``:8080``.
    """
    for key in (
        "GMAIL_PUBLIC_BASE_URL",
        "GMAIL_REDIRECT_URI",  # backward compatibility; endpoint is stripped
        "SERVICE_URL_GMAIL-AUTH",
        "SERVICE_URL_GMAIL_AUTH",
        # Backward compatibility with v61/v63 generated variables.
        "SERVICE_URL_GMAIL-AUTH_8080",
        "SERVICE_URL_GMAIL_AUTH_8080",
        "SERVICE_FQDN_GMAIL-AUTH",
        "SERVICE_FQDN_GMAIL_AUTH",
        "COOLIFY_URL",
    ):
        base = _normalize_public_base_url(os.getenv(key, ""))
        if base:
            return base
    return ""


def _endpoint(base: str, path: str) -> str:
    return f"{base.rstrip('/')}/{path.lstrip('/')}" if base else ""


# Backward-compatible helpers retained for older tests and local tooling.
def _normalize_callback_url(value: str) -> str:
    return _endpoint(_normalize_public_base_url(value), "/gmail/callback")


def _resolve_gmail_redirect_uri() -> str:
    return _endpoint(_resolve_gmail_public_base_url(), "/gmail/callback")


@dataclass(frozen=True)
class ScanPreset:
    key: str
    title: str
    symbols: list[str]


SCAN_PRESETS: dict[str, ScanPreset] = {
    "gold": ScanPreset("gold", "Gold 30d", ["XAU_USDT"]),
    "btc": ScanPreset("btc", "BTC 30d", ["BTC_USDT"]),
    "eth": ScanPreset("eth", "ETH 30d", ["ETH_USDT"]),
    "silver": ScanPreset("silver", "Silver 30d", ["SILVER_USDT"]),
    "oil": ScanPreset("oil", "Oil 30d", ["USOIL_USDT"]),
    "multi": ScanPreset("multi", "Multi 5 assets 30d", ["XAU_USDT", "BTC_USDT", "ETH_USDT", "SILVER_USDT", "USOIL_USDT"]),
}

# Exact symbols used by scan buttons and Symbols check.
# No automatic fallback/substitution is used, because XAU vs XAUT and WTI vs Brent have different prices.
SYMBOL_CANDIDATES: dict[str, list[str]] = {
    "gold": ["XAU_USDT"],      # GOLD(XAU)USDT
    "btc": ["BTC_USDT"],
    "eth": ["ETH_USDT"],
    "silver": ["SILVER_USDT"], # SILVER(XAG)USDT
    "oil": ["USOIL_USDT"],     # OIL(WTI)USDT
}


@dataclass(frozen=True)
class Settings:
    telegram_bot_token: str
    admin_telegram_id: int | None
    data_root: Path
    telegram_send_limit_mb: int
    days_back: int
    base_interval: str
    mexc_base_url: str
    mexc_market_type: str
    min_coverage_ratio: float
    min_effective_days: float
    intraday_scan_interval_sec: int
    intraday_days_back: int
    secret_encryption_key: str | None
    gmail_client_id: str
    gmail_client_secret: str
    gmail_public_base_url: str
    gmail_redirect_uri: str
    gmail_health_url: str
    gmail_send_to: str | None
    gmail_auto_send_archives: bool
    gmail_max_attachment_mb: int
    gmail_oauth_listen_host: str
    gmail_oauth_listen_port: int
    gmail_backup_root: Path | None
    app_version: str

    @property
    def candles_dir(self) -> Path:
        return self.data_root / "candles"

    @property
    def charts_dir(self) -> Path:
        return self.data_root / "charts"

    @property
    def meta_dir(self) -> Path:
        return self.data_root / "meta"

    @property
    def exports_dir(self) -> Path:
        return self.data_root / "exports"

    @property
    def logs_dir(self) -> Path:
        return self.data_root / "logs"

    @property
    def state_dir(self) -> Path:
        return self.data_root / "state"

    @property
    def secrets_dir(self) -> Path:
        return self.data_root / "secrets"

    @property
    def work_dir(self) -> Path:
        return self.data_root / "work"

    def ensure_dirs(self) -> None:
        for path in [
            self.candles_dir,
            self.charts_dir,
            self.meta_dir,
            self.exports_dir,
            self.logs_dir,
            self.state_dir,
            self.secrets_dir,
            self.work_dir,
        ]:
            path.mkdir(parents=True, exist_ok=True)


def load_settings() -> Settings:
    load_dotenv()
    token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    admin_raw = os.getenv("ADMIN_TELEGRAM_ID", "").strip()
    admin_id = int(admin_raw) if admin_raw.isdigit() else None
    data_root = Path(os.getenv("DATA_ROOT", "./storage")).expanduser().resolve()
    gmail_public_base_url = _resolve_gmail_public_base_url()
    backup_raw = os.getenv("GMAIL_BACKUP_ROOT", "").strip()
    gmail_backup_root = Path(backup_raw).expanduser().resolve() if backup_raw else None

    settings = Settings(
        telegram_bot_token=token,
        admin_telegram_id=admin_id,
        data_root=data_root,
        telegram_send_limit_mb=int(os.getenv("TELEGRAM_SEND_LIMIT_MB", "48")),
        days_back=int(os.getenv("DAYS_BACK", "30")),
        base_interval=os.getenv("BASE_INTERVAL", "1m").strip(),
        mexc_base_url=os.getenv("MEXC_BASE_URL", "https://api.mexc.com").strip().rstrip("/"),
        mexc_market_type="futures",
        min_coverage_ratio=float(os.getenv("MIN_COVERAGE_RATIO", "0.80")),
        min_effective_days=float(os.getenv("MIN_EFFECTIVE_DAYS", "20")),
        intraday_scan_interval_sec=int(os.getenv("INTRADAY_SCAN_INTERVAL_SEC", "300")),
        intraday_days_back=max(30, int(os.getenv("INTRADAY_DAYS_BACK", "30"))),
        secret_encryption_key=(
            os.getenv("SECRET_ENCRYPTION_KEY", "").strip()
            or os.getenv("GMAIL_STABLE_ENCRYPTION_KEY", "").strip()
            or os.getenv("SERVICE_REALBASE64_32_GMAIL-STORE", "").strip()
            or None
        ),
        gmail_client_id=os.getenv("GMAIL_CLIENT_ID", "").strip(),
        gmail_client_secret=os.getenv("GMAIL_CLIENT_SECRET", "").strip(),
        gmail_public_base_url=gmail_public_base_url,
        gmail_redirect_uri=_endpoint(gmail_public_base_url, "/gmail/callback"),
        gmail_health_url=_endpoint(gmail_public_base_url, "/healthz"),
        gmail_send_to=os.getenv("GMAIL_SEND_TO", "").strip() or None,
        gmail_auto_send_archives=os.getenv("GMAIL_AUTO_SEND_ARCHIVES", "true").strip().lower() in {"1", "true", "yes", "on"},
        gmail_max_attachment_mb=max(1, int(os.getenv("GMAIL_MAX_ATTACHMENT_MB", "24"))),
        gmail_oauth_listen_host=os.getenv("GMAIL_OAUTH_LISTEN_HOST", "0.0.0.0").strip() or "0.0.0.0",
        gmail_oauth_listen_port=int(os.getenv("GMAIL_OAUTH_LISTEN_PORT", "80")),
        gmail_backup_root=gmail_backup_root,
        app_version=APP_VERSION,
    )
    settings.ensure_dirs()
    return settings
